
# MediaWiki with MariaDB
#
# Access via "http://localhost:8082"
#   (or "http://$(docker-machine ip):8082" if using docker-machine)

version: '3'

services:

  mediawiki:
    image: mediawiki
    container_name: mw-mediawiki
    restart: always
    ports:
      - ${MEDIAWIKI_PORT}:80
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - mw-net

  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    container_name: mw-mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_ROOT_PASSWORD: 'Secret'
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: Example
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mw-net

  adminer:
    image: adminer
    container_name: mw-adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - mw-net

networks:
  mw-net:
    external: true

# An alternative way of defining a bind mount - needs absolute paths
#
# volumes:
#   images:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /path/to/images
#   db:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /path/to/db

# set formatoptions-=cro
